services:
  dnsmasq:
    image: dockurr/dnsmasq
    container_name: dnsmasq
    environment:
      DNS1: "1.0.0.1"
      DNS2: "1.1.1.1"
      DNS3: ""
      DNS4: ""
      CACHE_SIZE: "150"
      DOMAIN_NEEDED: "false"
      LOG_QUERIES: "false"
    ports:
      - 53:53/udp
      - 53:53/tcp
    cap_add:
      - NET_ADMIN
    restart: always
