on:
  pull_request:

name: "Review"

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  review:
    name: review
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Spelling
        uses: reviewdog/action-misspell@v1
        with:
          locale: "US"
          level: warning
          pattern: |
            *.md
            *.sh
          reporter: github-pr-review
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          level: warning
          reporter: github-pr-review
          hadolint_ignore: DL3059 SC3037 DL3018
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: YamlLint
        uses: reviewdog/action-yamllint@v1
        with:
          level: warning
          reporter: github-pr-review
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: ActionLint
        uses: reviewdog/action-actionlint@v1
        with:
          level: warning
          reporter: github-pr-review
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Shellformat
        uses: reviewdog/action-shfmt@v1
        with:
          level: warning
          shfmt_flags: "-i 2 -ci -bn"
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          level: warning
          reporter: github-pr-review
          shellcheck_flags: -x
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
